blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/SimpleAmericanAccent/saa-app-web/security/policy
    about: Please review our security policy for more details
